BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "SHRP_COMM_CD" (
	"GRP_CD"	TEXT,
	"SUB_CD"	TEXT,
	"SUB_NM"	TEXT,
	"DESC"	TEXT
);
CREATE TABLE IF NOT EXISTS "SHRP_ANAL_HST" (
	"ANAL_NO"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"SIMUL_NO"	INTEGER,
	"ANAL_DT"	NUMERIC,
	"IX_CD"	TEXT
);
CREATE TABLE IF NOT EXISTS "SHRP_SIMLATN_HST" (
	"SIMUL_NO"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"FILE_NM"	TEXT,
	"SIMUL_DT"	NUMERIC,
	"EXPER_CD"	TEXT,
	"AMPM_CD"	TEXT
);
CREATE TABLE IF NOT EXISTS "SHRP_TRAVTM" (
	"SIMUL_NO"	INTEGER,
	"CRP_NO"	INTEGER,
	"DRC"	TEXT,
	"DRC_CD"	TEXT,
	"VAL"	REAL
);
CREATE TABLE IF NOT EXISTS "SHRP_QLEN" (
	"SIMUL_NO"	INTEGER,
	"CRP_NO"	INTEGER,
	"DRC"	TEXT,
	"DRC_CD"	TEXT,
	"VAL"	REAL
);
CREATE TABLE IF NOT EXISTS "SHRP_VEHDELAY" (
	"SIMUL_NO"	INTEGER,
	"CRP_NO"	INTEGER,
	"DRC"	TEXT,
	"DRC_CD"	TEXT,
	"VAL"	REAL
);
CREATE TABLE IF NOT EXISTS "SHRP_STOPDELAY" (
	"SIMUL_NO"	INTEGER,
	"CRP_NO"	INTEGER,
	"DRC"	TEXT,
	"DRC_CD"	TEXT,
	"VAL"	REAL
);
CREATE TABLE IF NOT EXISTS "SHRP_SPEEDAVGHARM" (
	"SIMUL_NO"	INTEGER,
	"CRP_NO"	INTEGER,
	"DRC"	TEXT,
	"DRC_CD"	TEXT,
	"VAL"	REAL
);
CREATE TABLE IF NOT EXISTS "SHRP_VEHS" (
	"SIMUL_NO"	INTEGER,
	"CRP_NO"	INTEGER,
	"DRC"	TEXT,
	"DRC_CD"	TEXT,
	"VAL"	REAL
);
COMMIT;
