server:
  port: 8000

spring:
  datasource:
    url: jdbc:sqlite:/Users/nhn/test.db
    driver-class-name: org.sqlite.JDBC
    username:
    password:

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
    map-underscore-to-camel-case: true


